#define STEP_WHEELS_1A_PIN 9
#define STEP_WHEELS_2A_PIN 8
#define STEP_WHEELS_3A_PIN 7
#define STEP_WHEELS_4A_PIN 6

#define STEP_MOTOR_1A_PIN 1
#define STEP_MOTOR_2A_PIN 2
#define STEP_MOTOR_3A_PIN 3
#define STEP_MOTOR_4A_PIN 4